# Generated by Django 4.0.1 on 2022-07-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_last_name_profile_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='firstname',
            field=models.CharField(default='True', max_length=60, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='register',
            name='lastname',
            field=models.CharField(blank=True, max_length=60, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='register',
            name='middlename',
            field=models.CharField(blank=True, max_length=60, verbose_name='middle name'),
        ),
    ]
