# Generated by Django 4.0.1 on 2022-07-15 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_register_firstname_register_username_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='username',
            new_name='firstname',
        ),
    ]
