# Generated by Django 4.0.1 on 2022-07-15 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_delete_profile_rename_username_register_firstname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='register',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='register',
            name='middlename',
        ),
    ]
