# Generated by Django 4.0.1 on 2022-07-03 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_delete_user_bookcategory_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_firstname', models.CharField(max_length=100)),
                ('user_middlename', models.CharField(blank=True, max_length=100, null=True)),
                ('user_lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('password', models.CharField(blank=True, help_text='Use\'[algo]$[salt]$[hexdigest]\' or use the                 < a href="password/">change password form</a>.', max_length=128, null=True, verbose_name='password')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='bookcategory',
            options={'ordering': ['id'], 'verbose_name': 'BookCategory', 'verbose_name_plural': 'BookCategorys'},
        ),
        migrations.CreateModel(
            name='BookInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_inventory', to='book.book', verbose_name='book')),
            ],
            options={
                'verbose_name': 'BookInventory',
                'verbose_name_plural': 'BookInventories',
            },
        ),
    ]
