# Generated by Django 4.0.1 on 2022-07-04 08:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_user_alter_book_options_alter_bookcategory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_firstname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_lastname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_middlename',
        ),
        migrations.AddField(
            model_name='bookinventory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
