# Generated by Django 4.0.1 on 2022-07-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_delete_user_alter_bookcategory_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcategory',
            name='category_name',
            field=models.CharField(max_length=100, verbose_name='category_name'),
        ),
    ]
