# Generated by Django 4.0.1 on 2022-07-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_bookinventory_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book/'),
        ),
    ]
