# Generated by Django 4.0.1 on 2022-07-06 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Cart', 'verbose_name_plural': 'Carts'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'CartItem', 'verbose_name_plural': 'CartItems'},
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='price_ht',
        ),
    ]
