# Generated by Django 4.0.1 on 2022-07-05 01:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, verbose_name='user_id')),
                ('book_id', models.CharField(max_length=100, verbose_name='book_id')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('2.0'), max_digits=5, verbose_name='total')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='order_date')),
            ],
            options={
                'verbose_name': 'Order_detail',
                'verbose_name_plural': 'Order_details',
                'ordering': ['id'],
            },
        ),
    ]
