# Generated by Django 4.0.1 on 2022-07-05 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, verbose_name='order_id')),
                ('book_id', models.CharField(max_length=100, verbose_name='book_id')),
                ('quantity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quantity', to='order.order_detail', verbose_name='quantity')),
            ],
            options={
                'verbose_name': 'Order_items',
                'verbose_name_plural': 'Order_items',
            },
        ),
    ]
