# Generated by Django 4.0.1 on 2022-07-27 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_detail',
            name='book_id',
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
