# Generated by Django 4.0.1 on 2022-07-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_detail_book_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detail',
            name='payment_method',
            field=models.CharField(choices=[('Esewa', 'Esewa')], default='Esewa', max_length=10, verbose_name='payment_method'),
        ),
    ]
