# Generated by Django 4.0.1 on 2022-07-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_items_book_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_items',
            name='order_id',
            field=models.CharField(default=1, max_length=100, verbose_name='order_id'),
            preserve_default=False,
        ),
    ]
