# Generated by Django 4.0.1 on 2022-07-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_order_items_order_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_detail',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='order_detail',
            name='order_status',
            field=models.CharField(choices=[('pending', 'pending'), ('success', 'success')], default='pending', max_length=32),
        ),
    ]
