# Generated by Django 4.0.1 on 2022-07-31 10:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_detail_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='order_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, verbose_name='order_price'),
        ),
    ]
