# Generated by Django 4.0.1 on 2022-07-31 10:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_detail_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_items',
            name='order_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, verbose_name='order_quantity'),
        ),
    ]
