# Generated by Django 4.0.1 on 2022-07-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_order_items_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_items',
            name='order_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
